### ISSUE TITLE
Named object contexts might fight each other

### ISSUE THREAD

**Issue by mikeseghers** [appfoundry/Reliant#10]
Take the following situation:

A view controller bootstraps an object context. When an application would the initiate two instances of that view controller, living in memory at the same time (eg a detail view controller in a pager), those controllers will have a context with the same name. The current system (context registry et al) cannot deal with this situation. If other controllers now use the context as parent, reliant will always just retain the last created context. This is unintended behaviour. The whole named context system needs to be reviewed. It probably isn't the best idea.

**Comment by aceontech** [comment]
+1

**Comment by aceontech** [comment]
@mikeseghers See my [review branch](/appfoundry/Reliant/tree/review/named-contexts/Examples/Issue10ReviewExample). I have 2 instances of RandomViewController, each with their own object context, spawning their own instance of RandomViewModel, yet sharing the FibonacciViewModel inherited from the parent (AppWideConfiguration). 

I still need to create a configuration which depends on one of the nested configurations, but since the parent context's instance needs to be passed in explicitly, I don't think there'll be a problem with it. I'll try it out tomorrow.

Reaching into upper application layers to get a reference to the parent context is far from elegant though.. ([example](/appfoundry/Reliant/blob/review/named-contexts/Examples/Issue10ReviewExample/Issue10ReviewExample/Controller/RandomViewController.m#L29))

**Comment by mikeseghers** [comment]
I've responded to one of your comments in the code: https://github.com/appfoundry/Reliant/commit/9fe69f2db5ad0ce4665c5dfd89f29cddecfb8e0a

Could we do another conf call on this? I have a few ideas I want to bounce off.

**Comment by aceontech** [comment]
@mikeseghers I have some time today if you like.

Aren't 90% of child contexts referencing some kind of app-wide parent configuration? In that case, perhaps we could create a distinction between 'static' and 'instance' contexts, which would allow the following bootstrap syntax (obviously disregarding implementation details ;-)):

```objc
[self ocsBootstrapAndBindObjectContextWithConfiguratorFromClass:[NestedConfiguration class] 
                                                  parentContext:[AppConfiguration ocsObjectContext]];
```
(in this case -ocsObjectContext being a static property on AppConfiguration)

If this kind of syntax would be possible, we could retain the explicit passing of parent contexts, while covering most use cases. Further nested configurations which need a reference to an 'instance' context are usually passed their parent, either in the form of a `parentViewController` or `superview`.

**Comment by aceontech** [comment]
As discussed over Skype, I will look into an implementation which retains the current named context registry, while solving the name clashing issue.

**Comment by mikeseghers** [comment]
@aceontech if I am not mistaken, we fixed this in our latest release. Reopen if needed!
