### ISSUE TITLE
What about Widgets and Watch?

### ISSUE THREAD

**Issue by jaernouts** [appfoundry/Reliant#16]
Hello,

I'm trying to use reliant in my today widget and my watch kit extension, but (even when I call ocsInject) my dependencies aren't injected... Do I also need to call ocsBootstrapAndBindObjectContextWithConfiguratorFromClass somewhere on the widget/watch code itself (since they don't really use the AppDelegate)? If so, where, if not, can you help me to find out the issue..?

Thx!

**Comment by mikeseghers** [comment]
Hi Jens,

Since extensions are all running in different processes, you would indeed need to bootstrap (and bind) a reliant context for them. For WatchKit (2.0) you should be able to use https://developer.apple.com/library/prerelease/watchos/documentation/WatchKit/Reference/WKExtensionDelegate_protocol/index.html#//apple_ref/doc/uid/TP40015523-CH1. (Can you confirm?)

For your app extensions you should be able to use bootstrap (and bind) a context from your extension's main view controller. Another option would be to bind it to the extensionContext. Could you confirm this as well?

We should definitely add some examples of these different scenarios in our example app. Thanks for the great question! I'll keep this one open until you confirm and/or we add those examples.

**Comment by jaernouts** [comment]
Hi Mike,

Our WatchKit project is currently still using WatchOS 1, so I might need another solution for that.

Regarding the Widget, there's something weird going on. When I tried to bootstrap on the main ViewController itself, the dependencies are injected properly on that main ViewController. This is not the case when I use the extensionContext to bind on. But I'm using another class (some sort of data source) to handle the actual download, parse, ... of my data and in this class, my dependencies are nòt injected. I do call ocsInject on the init method, but they stay just nil. Do I need to bootstrap each class in the extension? This might be a bit weird since I already have to do ocsInject in each class where I need these dependencies...?

Thx already, and thx for the fast reply!

**Comment by mikeseghers** [comment]
Hi Jens,

At the moment, reliant doesn't really know watchkit/extensions/tvos, so it doesn't get any special treatment. If you bind a context to an object, that context's livecycle is just tied to the objects livecycle. If you use ocsInject, reliant will try to figure out what context to use, but in case of of the extension, it will probably not find the context by itself (the context resolution will first look for a context on self, then depending on what self is, look for contexts in eg a view controller hierarchy, and finally, look for a context on the AppDelegate (which you don't have in an extension). So you'll have to get a hold on the context yourself. 

That being said, it sounds like your "data source" class should actually be configured as a reliant object, defined in a configurator class. Objects created by reliant will automatically be injected. You should only ever use ocsInject if you are out of other options (eg. in a viewcontroller, which is created by a storyboard, and thus cannot be created by reliant). The whole point of reliant is that it lives outside of your code as much as possible. So my two cents from what I understand from your explanation:

- The view controller in the extension is the one responsible for bootstrapping a reliant context
- this reliant context holds (among other things) your data source object
- the data source object will get its proper dependencies injected since it lives in a context
- the data source object can be injected in the view controller via ocsInject

Hope this clarifies things for you.

**Comment by jaernouts** [comment]
Hi Mike,

Yes indeed, my datasource needs to be refactored so it's a reliant object on itself, but it's existing code and it's a pain in the ass to do that right now.. I'm refactoring step by step... ;-). 

Good to know that that will probably help and fix the issue, but at this moment - as I understand - it might be easier to bootstrap just my datasource since all my dependencies should be injected there...?

Thx for the great explanation!

**Comment by mikeseghers** [comment]
You could do that, but you will have to figure out how to get a hold on the context in the other parts of your code then. (Accessing the context isn't hard, but it's a bit of an antipattern to access it through your data source object...)

Maybe you could introduce a singleton object which bootstraps and holds the root reliant context. You can then use it as access point of the reliant context, just until you are done refactoring. Then you should be able to remove the singleton object from your code again.

**Comment by jaernouts** [comment]
Ok, that sounds like a plan! I'll try to work around that issue as long as I don't refactor the other part of my code...

Thx!

**Comment by jaernouts** [comment]
I changed some things in my cocoa pods configuration, and for some reason now my widget doesn't compile anymore. Don't really know why it did work before, since the error seems reasonable:

![screen shot 2016-04-26 at 12 51 17](https://cloud.githubusercontent.com/assets/2519801/14815780/999fd456-0bad-11e6-9c34-cd3ac6f0f5ec.png)


Can you take a look please? Thanks!

**Comment by mikeseghers** [comment]
Hi Jens,

this is all related to the fact that reliant isn't made for the watch yet. I'll try to make some time in the near future to give it a look, but do feel free to contribute!

**Comment by mikeseghers** [comment]
Hi Jens, I think we can now close this one, right? You do the honours?

**Comment by jaernouts** [comment]
Super, thanks for the great, fast, response and help!
